debug: true
spring:
  application:
    name: bin
  datasource:
    url: jdbc:mysql://localhost:3306/bins
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8200

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs